# Generated by Django 3.0.2 on 2020-02-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200129_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phoneNumber', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
