# Generated by Django 3.0.2 on 2020-02-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='zip_Code',
            new_name='zip_code',
        ),
    ]
